Update utils.py
Passing WindowsPath variable types to utils.get_mime() will return an error:
  File "C:\Python3\lib\site-packages\firstcontact\firstcontact.py", line 544, in <module>
    __main()
  File "C:\Python3\lib\site-packages\firstcontact\firstcontact.py", line 512, in __main
    mime = firstcontact.utils.get_mime(file)
  File "C:\Python3\lib\site-packages\firstcontact\utils.py", line 85, in get_mime
    mime = m.from_file(file_path)
  File "C:\Python3\lib\site-packages\magic\magic.py", line 89, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "C:\Python3\lib\site-packages\magic\magic.py", line 255, in magic_file
    return _magic_file(cookie, coerce_filename(filename))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type

Now the path will be converted to String.